2024-08-18 21:10:48,992:DEBUG:certbot._internal.main:certbot version: 2.11.0
2024-08-18 21:10:48,992:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-08-18 21:10:48,992:DEBUG:certbot._internal.main:Arguments: ['--standalone', '-d', 'mail.kelseywilliams.co']
2024-08-18 21:10:48,993:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-08-18 21:10:49,011:DEBUG:certbot._internal.log:Root logging level set at 30
2024-08-18 21:10:49,014:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2024-08-18 21:10:49,014:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7f6335627a70>
Prep: True
2024-08-18 21:10:49,014:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x7f6335627a70> and installer None
2024-08-18 21:10:49,015:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2024-08-18 21:10:49,103:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1897939826', new_authzr_uri=None, terms_of_service=None), 0eb69800aa12960aa76c2b6390c825ce, Meta(creation_dt=datetime.datetime(2024, 8, 18, 19, 10, 3, tzinfo=<UTC>), creation_host='79f72aa4a189', register_to_eff=None))>
2024-08-18 21:10:49,104:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-08-18 21:10:49,107:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-08-18 21:10:49,227:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-08-18 21:10:49,228:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 18 Aug 2024 21:10:49 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "hINABvxq-Bo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-08-18 21:10:49,240:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): e5.o.lencr.org:80
2024-08-18 21:10:49,679:DEBUG:urllib3.connectionpool:http://e5.o.lencr.org:80 "POST / HTTP/1.1" 200 345
2024-08-18 21:10:49,680:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/mail.kelseywilliams.co/cert3.pem is signed by the certificate's issuer.
2024-08-18 21:10:49,681:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/mail.kelseywilliams.co/cert3.pem is: OCSPCertStatus.GOOD
2024-08-18 21:10:49,684:DEBUG:certbot._internal.display.obj:Notifying user: Certificate not yet due for renewal
2024-08-18 21:10:51,897:DEBUG:certbot._internal.display.obj:Notifying user: Renewing an existing certificate for mail.kelseywilliams.co
2024-08-18 21:10:51,900:DEBUG:acme.client:Requesting fresh nonce
2024-08-18 21:10:51,901:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-08-18 21:10:51,938:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-08-18 21:10:51,939:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 18 Aug 2024 21:10:51 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: Hj5k7jKgibDBD-QoSLpHn8huyrnjREoIcfPnsIBNlB4FG8ZXTwI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-08-18 21:10:51,939:DEBUG:acme.client:Storing nonce: Hj5k7jKgibDBD-QoSLpHn8huyrnjREoIcfPnsIBNlB4FG8ZXTwI
2024-08-18 21:10:51,939:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "mail.kelseywilliams.co"\n    }\n  ]\n}'
2024-08-18 21:10:51,942:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTg5NzkzOTgyNiIsICJub25jZSI6ICJIajVrN2pLZ2liREJELVFvU0xwSG44aHV5cm5qUkVvSWNmUG5zSUJObEI0Rkc4WlhUd0kiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "AuRBwoHanXtzDIjjQAJZ0I82vLuvJj2_UMcx70VhT8n9fR3iq-Uz24Lyods_ojG1F0qeyT7b98wchQs9RL2pGAMDs254-qIHcsCr8XLIKyW7n_n9EylsE_rAs21IyKVpQLcJV1uIIGSXFXFtfTO4NznCv5YfcjX0qBUxkypRaIMpMAnqrNKyo-yyFW1mU3FaVT0fjICb-mbdki871xT4CbIkGquCt8bYnYlMwfv-NYhwd2-gq7jCfQOUWH7tKN3B1ZDg1PkGp0fYvqyZLQan7sj0yaje4HaC-sxO-NXoUkXYOxKSEhvmgWbmClzd2sbIG0sDkPq6Ty4-t40fkHdCgg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIm1haWwua2Vsc2V5d2lsbGlhbXMuY28iCiAgICB9CiAgXQp9"
}
2024-08-18 21:10:52,007:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 328
2024-08-18 21:10:52,008:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sun, 18 Aug 2024 21:10:51 GMT
Content-Type: application/problem+json
Content-Length: 328
Connection: keep-alive
Boulder-Requester: 1897939826
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://letsencrypt.org/docs/rate-limits>;rel="help"
Replay-Nonce: u9f3N-xzdqtp8_6tgIGzlKYrOKuhU_gJadmkWQwq5W3FQYIznJw
Retry-After: 117314

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mail.kelseywilliams.co, retry after 2024-08-20T05:46:06Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/",
  "status": 429
}
2024-08-18 21:10:52,008:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 131, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 399, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 137, in new_order
    response = self._post(self.directory['newOrder'], order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 365, in _post
    return self.net.post(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 738, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 751, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/acme/acme/client.py", line 602, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mail.kelseywilliams.co, retry after 2024-08-20T05:46:06Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
2024-08-18 21:10:52,012:ERROR:certbot._internal.log:An unexpected error occurred:
2024-08-18 21:10:52,012:ERROR:certbot._internal.log:Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mail.kelseywilliams.co, retry after 2024-08-20T05:46:06Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
